team-abcdedu/abcdedu-backend

- src/main/java/com/abcdedu_backend/configs/HelloConfig.java
- src/main/java/com/abcdedu_backend/utils/Helloutil.java
> [chore] 공통 디렉토리 생성

- .github/ISSUE_TEMPLATE/issue-template-feature.md
- .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
- src/main/java/com/abcdedu_backend/configs/HelloConfig.java
- src/main/java/com/abcdedu_backend/utils/Helloutil.java
이슈 템플릿을 생성했습니다. main에 해버려서 develop으로 합치고 진행할게요
> [DOCS] 이슈 템플릿 생성 

- src/main/java/com/abcdedu_backend/configs/WebConfig.java
- src/main/java/com/abcdedu_backend/hello/HelloController.java
- src/main/java/com/abcdedu_backend/interceptor/LoginInterceptor.java
- src/main/java/com/abcdedu_backend/interceptor/Member.java
- src/main/java/com/abcdedu_backend/interceptor/MemberRole.java
- 임시 Member, MeberRole  class interceptor 폴더에 생성
- WebConfig 생성하여 WebMvcConfigurer 구현 및 로그인 인터셉터 추가
- LoginInterceptor 생성
- HelloController 에서 test
> [feat] #5 로그인 인터셉터 develop 브랜치에 merge

- build.gradle
- src/main/java/com/abcdedu_backend/configs/SwaggerConfig.java
- src/main/java/com/abcdedu_backend/post/PostController.java
- src/main/resources/application.yaml
- gradle 의존성 추가
- Config 파일 생성
- .yaml 설정
- 컨트롤러에서 사용 확인
> [feat] #9 Swagger 기능 추가

- .github/pull_request_template.md
- .github/workflows/cicd-dev.yml
- .gitignore
- src/main/java/com/abcdedu_backend/common/jwt/JwtValidation.java
- src/main/java/com/abcdedu_backend/configs/WebConfig.java
- src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
- src/main/java/com/abcdedu_backend/member/dto/response/MemberShortInfoResponse.java
- src/main/java/com/abcdedu_backend/member/service/MemberService.java
- src/test/java/com/abcdedu_backend/member/repository/MemberRepositoryTest.java
> [FEAT] #17 프로필 이름, role 조회 API 구현

- src/main/java/com/abcdedu_backend/comment/Comment.java
- src/main/java/com/abcdedu_backend/member/service/MemberService.java
> [fix] #19 build 실패 해결

- src/main/java/com/abcdedu_backend/configs/WebConfig.java
> [FIX] cors 에러 해결

- src/main/java/com/abcdedu_backend/contact/controller/ContactController.java
- src/main/java/com/abcdedu_backend/contact/dto/request/ContactCreateRequest.java
- src/main/java/com/abcdedu_backend/contact/dto/response/ContactGetResponse.java
- src/main/java/com/abcdedu_backend/contact/dto/response/ContactListResponse.java
- src/main/java/com/abcdedu_backend/contact/entity/Contact.java
- src/main/java/com/abcdedu_backend/contact/entity/ContactType.java
- src/main/java/com/abcdedu_backend/contact/service/ContactService.java
- src/main/java/com/abcdedu_backend/exception/ErrorCode.java
- src/main/java/com/abcdedu_backend/post/controller/PostController.java
- 상담 타입을 requestBody로 받는다.
- 전반적인 Controller 구성 변경
#45
> [refactor] #45 상담 기능 request, response 변경

- src/main/java/com/abcdedu_backend/post/entity/Post.java
- src/main/java/com/abcdedu_backend/post/service/CommentService.java
- check 함수에서 void가 아니라 Post를 반환하는 CommentService.CheckPostAllowedComment() 함수 수정
> [fix] #42 check 메서드 수정

- .gitignore
- src/main/java/com/abcdedu_backend/configs/WebConfig.java
> [FIX] Cors 설정 수정

- src/main/java/com/abcdedu_backend/contact/controller/ContactController.java
- src/main/java/com/abcdedu_backend/contact/dto/request/ContactCreateRequest.java
> [FIX] 문의 조회 오류 #52

- src/main/java/com/abcdedu_backend/contact/controller/ContactController.java
- src/main/java/com/abcdedu_backend/contact/dto/request/ContactCreateRequest.java
- src/main/java/com/abcdedu_backend/contact/service/ContactService.java
> [FIX] 문의 조회 오류(2) #52

- .github/workflows/cicd-dev.yml
application.yaml을 .gitignore에 추가하면서 resources 폴더가 사라진 에러 해결.
> [FIX] resources 폴더 생성 추가

- .gitignore
- src/main/java/com/abcdedu_backend/configs/WebConfig.java
- src/main/java/com/abcdedu_backend/member/controller/AuthController.java
> [FIX] Cookie SameSite 문제 해결

- src/main/java/com/abcdedu_backend/common/jwt/JwtValidateArgumentResolver.java
- src/main/java/com/abcdedu_backend/global/jwt/JwtUtil.java
- src/main/java/com/abcdedu_backend/global/security/AuthorizationJwtHeaderFilter.java
- src/main/java/com/abcdedu_backend/global/security/JwtAuthenticationToken.java
- src/main/java/com/abcdedu_backend/global/security/JwtProvider.java
- src/main/java/com/abcdedu_backend/global/security/LoginUserDetails.java
- src/main/java/com/abcdedu_backend/global/security/RoleQueryFilter.java
- src/main/java/com/abcdedu_backend/global/security/SecurityConfig.java
- src/main/java/com/abcdedu_backend/member/service/MemberService.java
- src/test/java/com/abcdedu_backend/member/service/MemberServiceTest.java
1. jjwt(0.12.6) 버전에 따른 메소드 마이그레이션을 진행하였습니다.
2. 시큐리티 필터적용
jwt발급시에 role 발급코드가 없어서 우선 role조회는 filter를 따로 만들었습니다.
`/api/v1`이라는 공통주소가 설정에 있는걸 확인했습니다.
이런 사용이 안티패턴이라고 생각하는데 (일관적인 주소 prefix로 인해 h2-console주소변경, swagger주소변경, 시큐리티 설정시에는 /api/v1 prefix 제거해야작동, 공통설정으로인해 모든 api에 `/api/v1`적용->v2적용시 `api/v1/v2`로 표시) 
해당 코드에 대한 히스토리가 있나요??
```yml
server:
servlet:
context-path: /api/v1
```
> [Feat] security 57

- src/main/java/com/abcdedu_backend/member/controller/AuthController.java
> [fix] #64 쿠키 도메인 설정 해제

- src/main/java/com/abcdedu_backend/homework/dto/HomeworkReq.java
- src/main/java/com/abcdedu_backend/homework/dto/HomeworkRes.java
> [fix]: 과제 API 스펙 수정

- src/main/java/com/abcdedu_backend/infra/file/FileDirectory.java
- src/main/java/com/abcdedu_backend/lecture/controller/LectureController.java
- src/main/java/com/abcdedu_backend/lecture/controller/LectureControllerV2.java
- src/main/java/com/abcdedu_backend/lecture/entity/AssignmentAnswerFile.java
- src/main/java/com/abcdedu_backend/lecture/entity/AssignmentFile.java
- src/main/java/com/abcdedu_backend/lecture/entity/AssignmentType.java
- src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
- src/main/java/com/abcdedu_backend/member/controller/AuthController.java
- src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
> [FEAT] 클래스 기능 추가

- .github/workflows/cicd-prod.yml
cicd 중 application.yaml이 만들어지지 않는 에러 해결
> [HOTFIX] cicd 에러 해결

- src/main/java/com/abcdedu_backend/post/controller/PostController.java
- src/main/java/com/abcdedu_backend/post/service/PostService.java
> [FIX] #81게시글 요청 타입 변경, 수정 로직 변경

- src/main/java/com/abcdedu_backend/lecture/dto/request/CreateLectureRequest.java
- src/main/java/com/abcdedu_backend/lecture/dto/response/GetClassResponse.java
- src/main/java/com/abcdedu_backend/lecture/entity/Lecture.java
- src/main/java/com/abcdedu_backend/lecture/entity/SubLecture.java
- src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
- src/main/java/com/abcdedu_backend/lecture/service/LectureServiceV2.java
> [REFACTOR] #76 클래스 정보 변경

- src/main/java/com/abcdedu_backend/lecture/controller/LectureController.java
- src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
- src/main/java/com/abcdedu_backend/post/controller/PostController.java
- src/main/java/com/abcdedu_backend/post/dto/response/PostListResponse.java
- src/main/java/com/abcdedu_backend/post/service/PostService.java
이전 merge에서 에러 났던거 임시방편 해두었습니다 !
> Feat/post #83

- src/main/java/com/abcdedu_backend/post/controller/PostController.java
- src/main/java/com/abcdedu_backend/post/dto/response/PostListResponse.java
- src/main/java/com/abcdedu_backend/post/dto/response/PostResponse.java
- src/main/java/com/abcdedu_backend/post/entity/Post.java
- src/main/java/com/abcdedu_backend/post/service/PostService.java
> [FEAT] #83 Post 기능 고도화

- src/main/java/com/abcdedu_backend/member/entity/Member.java
- src/main/java/com/abcdedu_backend/post/controller/PostController.java
- src/main/java/com/abcdedu_backend/post/service/PostService.java
등업을 허용하는 사람은 관리자 이상이여야 한다.
해당 글의 작성자 기준으로 동작
> [feat] #30 등업 기능 1차 구현

- src/main/java/com/abcdedu_backend/infra/file/FileHandler.java
- src/main/java/com/abcdedu_backend/infra/file/LocalFileHandler.java
- src/main/java/com/abcdedu_backend/infra/file/S3FileHandler.java
- src/main/java/com/abcdedu_backend/lecture/controller/LectureController.java
- src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
- src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
- src/main/java/com/abcdedu_backend/member/service/MemberService.java
- src/main/java/com/abcdedu_backend/post/controller/PostController.java
- src/main/java/com/abcdedu_backend/post/service/PostService.java
- src/main/java/com/abcdedu_backend/utils/FileUtil.java
- src/test/java/com/abcdedu_backend/member/controller/MemberInfoControllerTest.java
- src/test/java/com/abcdedu_backend/member/service/MemberServiceTest.java
우선 이전 방식으로 변경했습니다. 파일 다운로드하고 저장하는 것보다는 Ec2에서 좋을것같아요.
> [REFACTOR] #91 파일 업로드 로직 성능 개선

- src/main/java/com/abcdedu_backend/homework/dto/response/HomeworkQuestionGetRes.java
- src/main/java/com/abcdedu_backend/homework/entity/HomeworkQuestion.java
- src/main/java/com/abcdedu_backend/homework/service/HomeworkService.java
- src/main/java/com/abcdedu_backend/post/controller/PostController.java
- src/main/java/com/abcdedu_backend/post/dto/response/CommentResponse.java
- src/main/java/com/abcdedu_backend/post/dto/response/PostResponse.java
- src/main/java/com/abcdedu_backend/post/entity/Post.java
- src/main/java/com/abcdedu_backend/post/service/CommentService.java
- src/main/java/com/abcdedu_backend/post/service/PostService.java
- src/main/java/com/abcdedu_backend/survey/controller/SurveyController.java
- src/main/java/com/abcdedu_backend/survey/service/SurveyService.java
> [FIX] #93 게시글, 댓글, 과제 관련 오류 해결

- .github/workflows/cicd-dev.yml
- .github/workflows/cicd-prod.yml
- src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
- src/main/java/com/abcdedu_backend/member/dto/response/MemberBasicInfoResponse.java
- src/main/java/com/abcdedu_backend/member/service/MemberService.java
- src/test/java/com/abcdedu_backend/member/controller/MemberInfoControllerTest.java
- src/test/java/com/abcdedu_backend/member/service/MemberServiceTest.java
email을 추가로 받게 되서 API를 하나 추가했습니다.
> [FEAT] 멤버 기본 정보 조회 API 구현

- .github/workflows/cicd-dev.yml
- .github/workflows/cicd-prod.yml
- src/main/java/com/abcdedu_backend/exception/ErrorCode.java
- src/main/java/com/abcdedu_backend/lecture/controller/LectureController.java
- src/main/java/com/abcdedu_backend/lecture/entity/AssignmentFile.java
- src/main/java/com/abcdedu_backend/lecture/entity/AssignmentType.java
- src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
- src/main/java/com/abcdedu_backend/member/dto/response/MemberInfoResponse.java
- src/main/java/com/abcdedu_backend/member/service/MemberService.java
> [REFACTOR] 운영 배포 전 리팩터링

- .github/workflows/cicd-dev.yml
- .github/workflows/cicd-prod.yml
- src/main/java/com/abcdedu_backend/exception/ErrorCode.java
- src/main/java/com/abcdedu_backend/lecture/controller/LectureController.java
- src/main/java/com/abcdedu_backend/lecture/entity/AssignmentFile.java
- src/main/java/com/abcdedu_backend/lecture/entity/AssignmentType.java
- src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
- src/main/java/com/abcdedu_backend/member/dto/response/MemberInfoResponse.java
- src/main/java/com/abcdedu_backend/member/service/MemberService.java
> [FIX] 멤버 정보 업데이트 API 수정

- src/main/java/com/abcdedu_backend/lecture/controller/LectureController.java
- src/main/java/com/abcdedu_backend/lecture/entity/AssignmentType.java
> [fix] #100 파일 등록 api 수정

- src/main/java/com/abcdedu_backend/lecture/controller/LectureController.java
- src/main/java/com/abcdedu_backend/lecture/entity/AssignmentType.java
- src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
- src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
- src/main/java/com/abcdedu_backend/member/service/MemberService.java
> [FIX] #100 파일 업로드 에러 수정

- src/main/java/com/abcdedu_backend/lecture/entity/SubLecture.java
>  [FIX] Lecture 엔티티 필드 길이 변경

- src/main/java/com/abcdedu_backend/exception/ExceptionManager.java
> [feat] DB 관련 에러를 처리해 줄 databaseExceptionHandler 생성

- src/main/java/com/abcdedu_backend/configs/WebConfig.java
> [FIX] #108 Cors 설정 추가

- src/main/java/com/abcdedu_backend/exception/ErrorCode.java
- src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
- src/main/java/com/abcdedu_backend/post/service/PostService.java
- src/main/java/com/abcdedu_backend/survey/service/SurveyService.java
> [Feat] 새싹 회원 검증 로직 추가 

- build.gradle
- deploy.sh
- docker-compose.yml
- prometheus.yml
- src/main/java/com/abcdedu_backend/global/security/SecurityConfig.java
- yml 파일 수정 되서 notion에 추가했습니다.
> [FEAT] #121 프로메테우스, 그라파나 모니터링 추가

- src/main/java/com/abcdedu_backend/global/security/SecurityConfig.java
> [fix] #125 security jwt 500 에러 해결

- src/main/java/com/abcdedu_backend/global/security/AuthorizationJwtHeaderFilter.java
- src/main/java/com/abcdedu_backend/global/security/JwtProvider.java
- src/main/java/com/abcdedu_backend/global/security/SecurityConfig.java
> [fix] #128 spring security 예외 처리 핸들링 오류 수정

- src/main/java/com/abcdedu_backend/survey/service/SurveyService.java
> [fix] #132 survey 조회 시, 역할 검증 로직 수정

- src/main/java/com/abcdedu_backend/post/service/CommentService.java
> [feat] #134 댓글 조회 기능 변경

- terraform/acm.tf
- terraform/alb.tf
- terraform/sg.tf
- terraform/variables.tf
급해서 AWS 홈페이지에서 직접 만들었던 alb, acm 추가했습니다. 
terraform import해서 변경사항 없이 적용했습니다.
> [BUILD] #130 AWS 수정사항 적용

- README.md
> [DOCS] #142 README.md 작성

- src/main/java/com/abcdedu_backend/post/entity/Post.java
- src/main/java/com/abcdedu_backend/post/service/PostService.java
> [fix] #144 post 조회 시 조회수가 증가가 되지 않는 버그 발견하여 수정 

- src/main/java/com/abcdedu_backend/member/controller/AdminMemberController.java
- src/main/java/com/abcdedu_backend/member/dto/request/ChangeMemberRoleRequest.java
- src/main/java/com/abcdedu_backend/member/dto/request/MemberSearchCondition.java
- src/main/java/com/abcdedu_backend/member/dto/response/AdminSearchMemberResponse.java
> [FEAT] #141 관리자 멤버 조회, 일괄 등업 기능 API 명세 merge

- src/main/java/com/abcdedu_backend/member/dto/request/SignUpRequest.java
- src/main/java/com/abcdedu_backend/member/service/MemberService.java
- src/test/java/com/abcdedu_backend/member/controller/AuthControllerTest.java
- src/test/java/com/abcdedu_backend/member/service/MemberServiceTest.java
> [refactor] #137 회원가입시 학번, 학교 추가

- src/main/java/com/abcdedu_backend/member/controller/EmailController.java
- src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
- src/main/java/com/abcdedu_backend/member/dto/request/SendMailRequest.java
- src/main/java/com/abcdedu_backend/member/dto/request/UpdatePasswordRequest.java
- src/main/java/com/abcdedu_backend/member/service/EmailService.java
- src/main/java/com/abcdedu_backend/member/service/MemberService.java
- src/main/java/com/abcdedu_backend/utils/RandomCodeGenerator.java
- src/test/java/com/abcdedu_backend/member/controller/MemberInfoControllerTest.java
비밀번호 변경할 때 보안 문제가 생길것으로 우려되서 임시 비밀번호 발급 방식으로 변경합니다.
> [refactor] #152 비밀번호 변경 방식 수정

- src/main/java/com/abcdedu_backend/member/controller/EmailController.java
- src/main/java/com/abcdedu_backend/member/service/EmailService.java
> [fix] #157 회원가입 인증 메시지 제목 수정

- src/main/java/com/abcdedu_backend/member/controller/AuthController.java
- src/main/java/com/abcdedu_backend/member/service/MemberService.java
- src/test/java/com/abcdedu_backend/member/controller/AuthControllerTest.java
> [fix] #160 admin 회원가입 api 제거

- src/main/java/com/abcdedu_backend/exception/ErrorCode.java
- src/main/java/com/abcdedu_backend/member/controller/AdminMemberController.java
- src/main/java/com/abcdedu_backend/member/repository/AdminMemberRepository.java
- src/main/java/com/abcdedu_backend/member/service/AdminMemberService.java
- src/test/java/com/abcdedu_backend/member/repository/AdminMemberRepositoryTest.java
- src/test/java/com/abcdedu_backend/member/service/AdminMemberServiceTest.java
> [FEAT] #156 등급 일괄 변경 기능

- src/main/java/com/abcdedu_backend/post/service/PostService.java
updatePostViwe() 함수가 @Transactional 바깥에 있어 적용이 안되어 viewCou…nt가 증가되지 못했던 버그 수정
> [FIX] #163 postViewCount 증가 로직 적용 불가 버그 수정

- src/main/java/com/abcdedu_backend/configs/AsyncConfig.java
- src/main/java/com/abcdedu_backend/member/service/EmailService.java
이메일 전송이 4~5초에서 밀리초 단위로 개선되었습니다.
> [refactor] #169 이메일 인증 방식 비동기로 전환

- src/main/java/com/abcdedu_backend/contact/controller/AdminContactController.java
- src/main/java/com/abcdedu_backend/contact/controller/ContactController.java
- src/main/java/com/abcdedu_backend/homework/controller/AdminHomeworkController.java
- src/main/java/com/abcdedu_backend/homework/controller/HomeworkController.java
- src/main/java/com/abcdedu_backend/survey/controller/AdminSurveyController.java
- src/main/java/com/abcdedu_backend/survey/controller/SurveyController.java
상담 조회, 과제/설문 결과 조회에 대한 api를 어드민 전용 url로 분리
> [REFACT] #176 어드민 url 분리

- src/main/java/com/abcdedu_backend/board/Board.java
- src/main/java/com/abcdedu_backend/board/BoardController.java
- src/main/java/com/abcdedu_backend/board/BoardService.java
- src/main/java/com/abcdedu_backend/post/controller/PostController.java
- src/main/java/com/abcdedu_backend/post/dto/request/PostCreateRequestV2.java
- src/main/java/com/abcdedu_backend/post/entity/Post.java
- src/main/java/com/abcdedu_backend/post/repository/PostReposiroty.java
- src/main/java/com/abcdedu_backend/post/service/PostService.java
- src/main/resources/db/migration/V2__add_boards_document.sql
> [Feat] #164 자료실 생성 

- src/main/java/com/abcdedu_backend/exception/ErrorCode.java
- src/main/java/com/abcdedu_backend/member/entity/Member.java
- src/main/java/com/abcdedu_backend/member/repository/AdminMemberRepository.java
- src/main/java/com/abcdedu_backend/member/service/MemberService.java
- src/main/java/com/abcdedu_backend/post/dto/PostNavigation.java
- src/main/java/com/abcdedu_backend/post/dto/response/PostResponse.java
- src/main/java/com/abcdedu_backend/post/repository/PostReposiroty.java
- src/main/java/com/abcdedu_backend/post/service/PostService.java
- src/test/java/com/abcdedu_backend/member/service/MemberServiceTest.java
- src/test/java/com/abcdedu_backend/post/service/PostServiceTest.java
> [feat] 게시글 조회시 이전,다음 id 추가

- src/main/java/com/abcdedu_backend/infra/file/FileDirectory.java
- src/main/java/com/abcdedu_backend/post/controller/CommentController.java
- src/main/java/com/abcdedu_backend/post/controller/PostController.java
- src/main/java/com/abcdedu_backend/post/dto/response/CommentResponse.java
- src/main/java/com/abcdedu_backend/post/entity/Comment.java
- src/main/java/com/abcdedu_backend/post/service/CommentService.java
- src/main/resources/db/migration/V2.0.2__add_object_key_column_to_comment.sql
> [refactor] 댓글에 첨부파일 첨부 추가

- src/main/java/com/abcdedu_backend/survey/controller/AdminSurveyController.java
- src/main/java/com/abcdedu_backend/survey/controller/SurveyController.java
- src/main/java/com/abcdedu_backend/survey/dto/response/SurveyListResponse.java
- src/main/java/com/abcdedu_backend/survey/service/SurveyService.java
> [Refact] 설문 도메인 관리자/일반 분리 and DTO 필드명 수정

- src/main/java/com/abcdedu_backend/post/dto/PostNavigation.java
- src/main/java/com/abcdedu_backend/post/repository/PostReposiroty.java
- src/main/java/com/abcdedu_backend/post/service/PostService.java
- src/test/java/com/abcdedu_backend/post/service/PostServiceTest.java
> [fix] #199 이전,다음 글 secret, writerEmail 추가 및 게시판 구분 추가

- src/main/java/com/abcdedu_backend/post/entity/Comment.java
- src/main/java/com/abcdedu_backend/post/service/CommentService.java
> [FIX] 파일 없는 댓글 조회시 에러 수정

- Dockerfile
> [fix]  aws 서버에 기본폰트가 없어 엑셀 파일 추출 중 에러 발생

- src/main/resources/db/migration/V2.0.5__change_post_content_length.sql
> [fix] #209 post 내용 글자 수 제한 에러

- src/main/resources/db/migration/V2.0.5__change_post_content_length.sql
Reverts team-abcdedu/abcdedu-backend#213
> Revert "[fix] #209 post 내용 글자 수 제한 에러"

- src/main/java/com/abcdedu_backend/homework/controller/AdminHomeworkController.java
- src/main/java/com/abcdedu_backend/homework/controller/AdminHomeworkReplyController.java
- src/main/java/com/abcdedu_backend/homework/dto/response/HomeworkRes.java
- src/main/java/com/abcdedu_backend/homework/repository/HomeworkRepository.java
- src/main/java/com/abcdedu_backend/homework/service/HomeworkService.java
> [FIX] 1회차 homework 프론트 개발자 건의사항 반영

- src/main/java/com/abcdedu_backend/homework/controller/AdminHomeworkController.java
- src/main/java/com/abcdedu_backend/homework/dto/request/RepresentativeRegisterRequest.java
- src/main/java/com/abcdedu_backend/homework/dto/response/HomeworkRes.java
- src/main/java/com/abcdedu_backend/homework/service/HomeworkAdminService.java
- src/test/java/com/abcdedu_backend/homework/controller/AdminHomeworkControllerTest.java
- src/test/java/com/abcdedu_backend/homework/repository/HomeworkRepresentativeRepositoryTest.java
> [Refactor] homework 관련 보완 반영

- src/main/java/com/abcdedu_backend/board/BoardController.java
- src/main/java/com/abcdedu_backend/post/controller/PostController.java
> [refactor] 구버전 코드 및 필요없는 '/' 매핑 삭제

- src/main/java/com/abcdedu_backend/exception/ErrorCode.java
- src/main/java/com/abcdedu_backend/homework/controller/AdminHomeworkReplyController.java
- src/main/java/com/abcdedu_backend/homework/dto/response/ReplyWithMemberResponse.java
- src/main/java/com/abcdedu_backend/homework/repository/HomeworkReplyRepository.java
- src/main/java/com/abcdedu_backend/homework/service/HomeworkReplyService.java
> [feat] #227 homework 응답 엑셀로 추출할 때 [학번, 학교] 칼럼 추가
